import type { Config } from "tailwindcss";

export default {
  content: [
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        /* Linq tokens */
        "deep-plum": "#4C3D73",
        "royal-indigo": "#5A4FCF",
        "slate-navy": "#2E3A59",
        graphite: "#1D1D22",
        "soft-white": "#F7F7F8",
        lavender: "#8B7BFF",
        "lavender-light": "#C4BBFF",
        "lavender-deep": "#B8ACFF",
        canvas: "#ffffff",
        surface: "#FAFAFC",
        border: "#E8E6F0",
        "text-primary": "#1D1D22",
        "text-muted": "#6B6B80",
        "text-xmuted": "#A0A0B0",
        error: "#E85454",

        /* Back-compat aliases */
        primary: {
          DEFAULT: "#5A4FCF",
          foreground: "#F7F7F8",
        },
        ink: "#1D1D22",
        "ink-deep": "#1D1D22",
        charcoal: "#1D1D22",
        slate: "#2E3A59",
        steel: "#6B6B80",
        stone: "#A0A0B0",
        "surface-soft": "#FAFAFC",
        "surface-yellow": "#fff8e0",
        "brand-yellow": "#ffd02f",
        "brand-yellow-deep": "#fcb900",
        "brand-blue": "#5A4FCF",
        "blue-pressed": "#4036B3",
        "yellow-dark": "#746019",
        hairline: "#E8E6F0",
        "hairline-soft": "#EFEDF6",
        "hairline-strong": "#D7D3E3",
        muted: "#A0A0B0",
        heading: "#1D1D22",
        "light-1": "#fff8e0",
        "light-2": "#FAFAFC",
        "light-3": "#F7F7F8",
        "primary-strong": "#1D1D22",
        success: "#00b473",
        "coral-light": "#ffc6c6",
        "rose-light": "#fde0f0",
        "teal-light": "#c3faf5",
      },
      fontFamily: {
        sans: ["var(--font-sans)", "DM Sans", "ui-sans-serif", "system-ui"],
        display: ["var(--font-sans)", "DM Sans", "ui-sans-serif", "system-ui"],
        mono: [
          "var(--font-mono)",
          "DM Mono",
          "ui-monospace",
          "SFMono-Regular",
          "Menlo",
          "Monaco",
          "Consolas",
          "\"Liberation Mono\"",
          "\"Courier New\"",
          "monospace",
        ],
        script: ["var(--font-script)", "cursive"],
      },
      borderRadius: {
        xs: "4px",
        sm: "4px",
        md: "8px",
        lg: "12px",
        xl: "20px",
        "2xl": "12px",
        "3xl": "14px",
        feature: "14px",
        full: "9999px",
      },
      spacing: {
        "section-sm": "48px",
        section: "64px",
        "section-lg": "96px",
        hero: "120px",
      },
    },
  },
  plugins: [],
} satisfies Config;
