import type { Config } from "tailwindcss";

export default {
  content: [
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: "#1c1c1e",
          foreground: "#ffffff",
        },
        ink: "#1c1c1e",
        "ink-deep": "#050038",
        charcoal: "#2c2c34",
        slate: "#555a6a",
        steel: "#6b6f7e",
        stone: "#8e91a0",
        canvas: "#ffffff",
        surface: "#f7f8fa",
        "surface-soft": "#fafbfc",
        "surface-yellow": "#fff8e0",
        "brand-yellow": "#ffd02f",
        "brand-yellow-deep": "#fcb900",
        "brand-blue": "#4262ff",
        "blue-pressed": "#2a41b6",
        "yellow-dark": "#746019",
        hairline: "#e0e2e8",
        "hairline-soft": "#eef0f3",
        "hairline-strong": "#c7cad5",
        border: "#e0e2e8",
        muted: "#a5a8b5",
        heading: "#1c1c1e",
        "light-1": "#fff8e0",
        "light-2": "#fafbfc",
        "light-3": "#f7f8fa",
        "primary-strong": "#2c2c34",
        success: "#00b473",
        "coral-light": "#ffc6c6",
        "rose-light": "#fde0f0",
        "teal-light": "#c3faf5",
      },
      fontFamily: {
        sans: ["var(--font-sans)", "Plus Jakarta Sans", "ui-sans-serif", "system-ui"],
        display: ["var(--font-display)", "Space Grotesk", "ui-sans-serif", "system-ui"],
      },
      borderRadius: {
        xs: "2px",
        sm: "4px",
        md: "6px",
        lg: "8px",
        xl: "10px",
        "2xl": "12px",
        "3xl": "14px",
        feature: "14px",
      },
      spacing: {
        "section-sm": "48px",
        section: "64px",
        "section-lg": "96px",
        hero: "120px",
      },
    },
  },
  plugins: [],
} satisfies Config;
