import Link from "next/link";
import GradientBackground from "@/components/GradientBackground";
import { Button } from "@/components/ui";
import { Info } from "lucide-react";
import { supabase, getFileUrl as getSupabaseFileUrl } from "@/lib/supabase";
import CardView from "./CardView";
import { CardData } from "@/types/card";
import { Metadata } from "next";

export async function generateMetadata(props: { params: Promise<{ id: string }> }): Promise<Metadata> {
  const params = await props.params;
  const { data: record } = await supabase
    .from("attendees")
    .select("name, event_name, card_preview_url")
    .eq("id", params.id)
    .single();

  if (!record) return { title: "Attendee Card | AVTIVE" };

  const ogImage = record.card_preview_url 
    ? getSupabaseFileUrl("card_previews", record.card_preview_url)
    : undefined;

  return {
    title: `${record.name}'s Attendee Card | ${record.event_name || 'AVTIVE'}`,
    description: `View the official attendee card for ${record.name} at ${record.event_name || 'the event'}. Generated by AVTIVE.`,
    openGraph: {
      title: `${record.name}'s Attendee Card`,
      description: `Official attendee profile for ${record.name}.`,
      type: 'website',
      images: ogImage ? [{ url: ogImage, width: 1200, height: 627, alt: `${record.name}'s Attendee Card` }] : [],
    },
    twitter: {
      card: 'summary_large_image',
      title: `${record.name}'s Attendee Card`,
      description: `Official attendee profile for ${record.name}.`,
      images: ogImage ? [ogImage] : [],
    }
  };
}

// This makes the page a Server Component
export default async function CardViewPage(props: { 
  params: Promise<{ id: string }>;
  searchParams: Promise<{ share?: string }>;
}) {
  const params = await props.params;
  const searchParams = await props.searchParams;
  const id = params.id;
  const isShareMode = searchParams?.share === "true";
  let card: CardData | null = null;

  try {
    // Fetch directly from Supabase
    const { data: record, error } = await supabase
      .from("attendees")
      .select("*")
      .eq("id", id)
      .single();
    
    if (error) throw error;
    
    if (record) {
      card = {
        id: record.id,
        name: record.name,
      
        role: record.role || "Attendee", 
        company: record.company,
        email: record.card_email,
        eventName: record.event_name,
        sessionDate: record.session_date,
        location: record.location,
        track: record.track,
        year: record.year,
        linkedin: record.linkedin,
        photo: record.photo_url ? getSupabaseFileUrl("attendee_photos", record.photo_url) : undefined,
        designType: record.design_type,
        color: record.card_color,
      };
    }
  } catch (err) {
    console.error("Server-side fetch error:", err);
    card = null;
  }

  if (!card) {
    return (
      <main className="relative min-h-screen w-full flex items-center justify-center p-6 text-center bg-transparent">
        <GradientBackground />
        <div className="relative z-10 flex flex-col items-center gap-4 glass-panel p-10 rounded-[12px] shadow-2xl max-w-sm animate-slide-up">
          <div className="w-12 h-12 rounded-full bg-surface flex items-center justify-center text-muted">
            <Info size={24} />
          </div>
          <div className="flex flex-col gap-1">
            <p className="text-heading font-semibold">Card not found</p>
            <p className="text-sm text-muted">
                The card you&apos;re looking for doesn&apos;t exist or my connection to the database is sleeping.
            </p>
          </div>
          {!isShareMode && (
            <Link href="/dashboard" className="mt-2">
              <Button variant="secondary">Back to Dashboard</Button>
            </Link>
          )}
        </div>
      </main>
    );
  }

  return <CardView card={card} isShareMode={isShareMode} />;
}