import Link from "next/link";
import GradientBackground from "@/components/GradientBackground";
import { Button } from "@/components/ui";
import { Info } from "lucide-react";
import { supabase, getFileUrl as getSupabaseFileUrl } from "@/lib/supabase";
import CardView from "./CardView";
import { CardData } from "@/types/card";
import { parseEventSponsors } from "@/lib/sponsors";
import { Metadata } from "next";
import { decryptAttendeeSensitiveFields } from "@/lib/security/attendee-sensitive";
import { getAdminClient } from "@/lib/admin";

export async function generateMetadata(props: { params: Promise<{ id: string }> }): Promise<Metadata> {
  const params = await props.params;
  const { data: record } = await supabase
    .from("attendees")
    .select("name, event_name, card_preview_url")
    .eq("id", params.id)
    .single();

  if (!record) return { title: "Attendee Card | AVTIVE" };

  const ogImage = record.card_preview_url 
    ? getSupabaseFileUrl("card_previews", record.card_preview_url)
    : undefined;

  return {
    title: `${record.name}'s Attendee Card | ${record.event_name || 'AVTIVE'}`,
    description: `View the official attendee card for ${record.name} at ${record.event_name || 'the event'}. Generated by AVTIVE.`,
    openGraph: {
      title: `${record.name}'s Attendee Card`,
      description: `Official attendee profile for ${record.name}.`,
      type: 'website',
      images: ogImage ? [{ url: ogImage, width: 1200, height: 627, alt: `${record.name}'s Attendee Card` }] : [],
    },
    twitter: {
      card: 'summary_large_image',
      title: `${record.name}'s Attendee Card`,
      description: `Official attendee profile for ${record.name}.`,
      images: ogImage ? [ogImage] : [],
    }
  };
}

// This makes the page a Server Component
export default async function CardViewPage(props: { 
  params: Promise<{ id: string }>;
  searchParams: Promise<{ share?: string }>;
}) {
  const params = await props.params;
  const searchParams = await props.searchParams;
  const id = params.id;
  const isShareMode = searchParams?.share === "true";
  let card: CardData | null = null;

  try {
    // Fetch directly from Supabase
    const { data: record, error } = await supabase
      .from("attendees")
      .select("*")
      .eq("id", id)
      .single();
    
    if (error) throw error;
    
    if (record) {
      const { row: secureRecord } = decryptAttendeeSensitiveFields(record);
      let sponsors = undefined as CardData["sponsors"];
      let organizationName = "";
      let organizationLogoUrl = "";
      if (secureRecord.event_id) {
        const { data: ev } = await supabase
          .from("events")
          .select("sponsors, user_id")
          .eq("id", secureRecord.event_id)
          .single();
        if (ev) {
          sponsors = parseEventSponsors(ev.sponsors);
          if (ev.user_id) {
            try {
              const admin = getAdminClient();
              const [{ data: userData }, { data: profileData }] = await Promise.all([
                admin.auth.admin.getUserById(ev.user_id),
                admin.from("profiles").select("organization_name").eq("id", ev.user_id).maybeSingle(),
              ]);
              organizationName =
                profileData?.organization_name ||
                (typeof userData?.user?.user_metadata?.organization_name === "string"
                  ? userData.user.user_metadata.organization_name
                  : "");
              organizationLogoUrl =
                typeof userData?.user?.user_metadata?.organization_logo_url === "string"
                  ? userData.user.user_metadata.organization_logo_url
                  : "";
            } catch (brandingErr) {
              console.error("Branding fetch failed:", brandingErr);
            }
          }
        }
      }

      card = {
        id: secureRecord.id,
        name: secureRecord.name,
      
        role: secureRecord.role || "Attendee", 
        company: secureRecord.company,
        email: secureRecord.card_email,
        eventName: secureRecord.event_name,
        sessionDate: secureRecord.session_date,
        sessionTime: secureRecord.session_time || undefined,
        location: secureRecord.location,
        track: secureRecord.track,
        year: secureRecord.year,
        linkedin: secureRecord.linkedin,
        photo: secureRecord.photo_url ? getSupabaseFileUrl("attendee_photos", secureRecord.photo_url) : undefined,
        designType: secureRecord.design_type,
        color: secureRecord.card_color,
        fontFamily: secureRecord.card_font || undefined,
        cardRole: secureRecord.track as "guest" | "visitor",
        sponsors,
        organizationName,
        organizationLogoUrl,
      };
    }
  } catch (err) {
    console.error("Server-side fetch error:", err);
    card = null;
  }

  if (!card) {
    return (
      <main className="relative min-h-screen w-full flex items-center justify-center p-6 text-center bg-transparent">
        <GradientBackground />
        <div className="relative z-10 flex flex-col items-center gap-4 glass-panel p-10 rounded-xl shadow-2xl max-w-sm animate-slide-up">
          <div className="w-12 h-12 rounded-full bg-surface flex items-center justify-center text-muted">
            <Info size={24} />
          </div>
          <div className="flex flex-col gap-1">
            <p className="text-heading font-semibold">Card not found</p>
            <p className="text-sm text-muted">
                The card you&apos;re looking for doesn&apos;t exist or my connection to the database is sleeping.
            </p>
          </div>
          {!isShareMode && (
            <Link href="/dashboard" className="mt-2">
              <Button variant="secondary">Back to Dashboard</Button>
            </Link>
          )}
        </div>
      </main>
    );
  }

  return <CardView card={card} isShareMode={isShareMode} />;
}